export enum SupportedCryptos {
  Bitcoin = "Bitcoin",
  Ethereum = "Ethereum",
  Cardano = "Cardano",
  Dogecoin = "Dogecoin",
  Litecoin = "Litecoin",
  Dash = "Dash",
  Ripple = "Ripple",
  "The Sandbox" = "The Sandbox",
  Decentraland = "Decentraland",
  "Binance Coin" = "Binance Coin",
  Solana = "Solana",
  Polkadot = "Polkadot",
  Avalanche = "Avalanche",
  Chainlink = "Chainlink",
  Algorand = "Algorand",
  Polygon = "Polygon",
  VeChain = "VeChain",
}
